name: android_app_info
description: Lets you query Android application info from a Flutter application.
version: 0.0.4
author: Ryan Gonzalez <rymg19@gmail.com>
homepage: https://github.com/kirbyfan64/android_app_info

flutter:
  plugin:
    androidPackage: com.refi64.androidappinfo
    pluginClass: AndroidAppInfoPlugin

dependencies:
  flutter:
    sdk: flutter
